-- MySQL Script generated by MySQL Workbench
-- Mon Sep 12 22:09:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema examen_fullstack
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema examen_fullstack
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `examen_fullstack` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `examen_fullstack` ;

-- -----------------------------------------------------
-- Table `examen_fullstack`.`t_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examen_fullstack`.`t_user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `tx_avatar` VARCHAR(128) NULL DEFAULT NULL,
  `tx_email` VARCHAR(32) NOT NULL,
  `tx_full_name` VARCHAR(64) NULL DEFAULT NULL,
  `tx_uid` VARCHAR(128) NOT NULL,
  `tx_pass` VARCHAR(128) NOT NULL,
  `tx_rol` VARCHAR(32) NOT NULL,
  `tx_user` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `UK_ibdm7h49yyuqogns1ym7espk5` (`tx_email` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
